---
base:
    packages: [
        vim, iotop, fail2ban, build-essential, libssl-dev, python-software-properties, git
    ]
    timezone: UTC
    locale: en_US.utf8
nginx:
    remove_default: true
    worker_processes: 2
    worker_connections: 1024
    client_body_buffer_size: 16k
    client_max_body_size: 64m
    vhosts:
        - servername: symfony3.dev
          docroot: /var/www/symfony3/web
          index: app_dev.php
        - servername: symfony2.dev
          docroot: /var/www/symfony2/web/
          index: app_dev.php
php:
    # support 5.6, 7.0
    version: 7.0
mariadb:
    version: 10.1
    root_password: root
    database: symfony
    user: linhnguyen
    password: 123456
nodejs:
    version: _5.x
    packages: [bower, gulp]
redis:
    redis_bind_ip: 127.0.0.1
    apt_cache_valid_time: 600
