---
- set_fact: php_socket="/var/run/php/php7.0-fpm.sock"
  when: php.version == 7.0

- set_fact: php_socket="/var/run/php/php5.6-fpm.sock"
  when: php.version != 7.0

- name: Install Nginx
  apt: pkg=nginx state=present

- name: Change default nginx config
  template: src=nginx.tpl dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Remove default nginx vhost (if configured)
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: nginx.remove_default
  notify: restart nginx

- name: Change default nginx site
  copy: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
  when: nginx.remove_default == false

- name: Enable default nginx site
  file: path=/etc/nginx/sites-enabled/default src=/etc/nginx/sites-available/default state=link
  notify: restart nginx
  when: nginx.remove_default == false

- name: Add nginx vhost
  template: src=vhost.tpl dest="/etc/nginx/sites-available/{{ item.servername }}.conf"
  notify: restart nginx
  with_items: "{{ nginx.vhosts }}"

- name: Create vhost symlink
  file: src="/etc/nginx/sites-available/{{ item.servername }}.conf" dest="/etc/nginx/sites-enabled/{{ item.servername }}.conf" state=link
  notify: restart nginx
  with_items: "{{ nginx.vhosts }}"
